global:
  scrape_interval:     5s
  evaluation_interval: 5s

#rule_files:
#  - "alerts/memory.yml"

# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - localhost:9093

scrape_configs:
  # - job_name: 'node'
  #   static_configs:
  #   - targets: ['localhost:9100']
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
