name: docker-automated-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 6
      matrix:
        TAG_NAME: [2.15.2, 2.15.1, 2.15.0, 2.14.0, 2.13.1, 2.13.0]

    steps:
    - uses: actions/checkout@v1
    - name: Install Trivy for Vulnerability Scanning of Docker images.
      run: |
        curl -fsSL https://raw.githubusercontent.com/darkwizard242/devopsubuntu1804/v1.0/packer-build/mods/27-trivy.sh | sudo bash -s -- install
    - name: Build docker image tag ${{ matrix.TAG_NAME }} & push to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_TOKEN }}
        dockerfile: Dockerfile
        build_args: version=${{ matrix.TAG_NAME }}
        repository: darkwizard242/prometheus
        tags: ${{ matrix.TAG_NAME }}
    - name: Run Trivy for Vulnerability Scanning of image
      run: |
        trivy darkwizard242/prometheus:${{ matrix.TAG_NAME }}
    - name: Archive and upload Dockerfile
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.TAG_NAME }}_image_artifacts
        path: .
